### ISSUE TITLE
Table is not tabling in footer

### ISSUE THREAD

**Issue by dmanalo16** [tulXoro/coll-trie-site#3]
![Issue](https://user-images.githubusercontent.com/91287580/184464894-9e7af98e-3b55-4044-b332-eda647c5a556.jpg)
Attempted to format footer links into table with descriptions, does not look good full screen and even worse half screen
![Half screen issue](https://user-images.githubusercontent.com/91287580/184464939-6a5e3118-65d4-4518-9937-c98b950bc8ae.jpg)

**Comment by tulXoro** [comment]
looks like a table now. the changes should be reflected on ur branch (branch_d)
